In [193]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [194]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [195]:
dataset.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [196]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [197]:
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [198]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [199]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [200]:
from sklearn.model_selection import train_test_split

In [201]:
x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.25)

In [202]:
from sklearn.preprocessing import StandardScaler

In [203]:
sc = StandardScaler()

In [204]:
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)

In [205]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [206]:
x_std_train = x_sc.fit_transform(x_train)
y_std_train = x_sc.fit_transform(t_train)

In [207]:
x_std_test = x_sc.transform(x_test)
y_std_test = x_sc.transform(t_test)

In [208]:
from sklearn.ensemble import RandomForestRegressor

In [209]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [210]:
r_reg = RandomForestRegressor(n_estimators = 250)

In [211]:
from sklearn.preprocessing import PolynomialFeatures

In [212]:
x_poly = PolynomialFeatures(degree = 5)
x_poly =x_poly.fit_transform(x_train)

In [213]:
r_reg.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=250, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [214]:
temp =  PolynomialFeatures(degree = 5)
temp = temp.fit_transform(x_test)

In [215]:
r_pred = r_reg.predict(x_test)

In [216]:
from sklearn.metrics import r2_score

In [217]:
r = r2_score(y_test,r_pred)

In [218]:
from sklearn.preprocessing import LabelEncoder

In [219]:
winered = LabelEncoder()

In [220]:
dataset['quality'] = winered.fit_transform(dataset['quality'])

In [221]:
dataset['quality'].value_counts()

2    681
3    638
4    199
1     53
5     18
0     10
Name: quality, dtype: int64

In [222]:
x = dataset.drop('quality',axis = 1).values
y = dataset.iloc[:,-1].values

In [223]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [224]:
y

array([2, 2, 2, ..., 3, 2, 3])

In [225]:
from sklearn.model_selection import train_test_split

In [226]:
x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.2)

In [227]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

1279
320
1279
320


In [228]:
from sklearn.preprocessing import MinMaxScaler

In [229]:
sc = MinMaxScaler()

In [230]:
sc.fit(dataset)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [231]:
sc = sc.transform(dataset)

In [232]:
from sklearn.preprocessing import StandardScaler

In [233]:
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)

In [234]:
x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.25)

In [235]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [236]:
x_std_train = x_sc.fit_transform(x_train)
y_std_train = x_sc.fit_transform(t_train)

In [237]:
x_std_test = x_sc.transform(x_test)
y_std_test = x_sc.transform(t_test)

In [238]:
x_test[:10,5:]

array([[16.     , 40.     ,  0.9991 ,  3.39   ,  0.62   ,  9.4    ],
       [17.     , 78.     ,  0.99346,  3.68   ,  0.73   , 11.4    ],
       [22.     , 89.     ,  0.9959 ,  3.34   ,  0.54   ,  9.2    ],
       [22.     , 91.     ,  0.9979 ,  3.29   ,  0.62   , 10.1    ],
       [36.     , 60.     ,  0.99494,  3.1    ,  0.4    ,  9.3    ],
       [15.     , 48.     ,  0.99502,  3.12   ,  0.48   , 10.     ],
       [19.     , 27.     ,  0.99545,  3.28   ,  0.73   , 11.9    ],
       [12.     , 56.     ,  0.9968 ,  3.49   ,  0.67   ,  9.2    ],
       [10.     , 52.     ,  0.9968 ,  3.23   ,  0.77   ,  9.5    ],
       [24.     , 32.     ,  0.99402,  3.54   ,  0.6    , 11.3    ]])

In [239]:
from sklearn.ensemble import RandomForestClassifier

In [240]:
r_cla = RandomForestClassifier()

In [241]:
r_cla.fit(x_train , y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [242]:
r_pred = r_cla.predict(x_test)

In [243]:
from sklearn.metrics import confusion_matrix

In [244]:
r_c = confusion_matrix(y_test , r_pred)

In [245]:
print(r_c)

[[  0   0   2   0   0   0]
 [  1   0   3   3   0   0]
 [  0   0 161  30   1   0]
 [  0   0  32 112   8   0]
 [  0   0   1  19  24   0]
 [  0   0   0   1   2   0]]


In [246]:
from sklearn.metrics import accuracy_score

In [247]:
r_acc = accuracy_score(y_test , r_pred)

In [250]:
print('Random Forest:' + str(r_acc))

Random Forest:0.7425


# CONCLUSION

We have solved it using *Regression & Classification technique*...!
    AS WE CAN SEE from the above results that the **RandomForest** is giving more efficiency than any other algorithmic techniques ,so we can conclude that **RandomForest is the best algorithmic technique for this data set.**

#                                         -  SNEHA.S
